### ISSUE TITLE
Switch from RHEL7 to CentOS7

### ISSUE THREAD

**Issue by bliemli** [appuio/appuio-pruner#1]
If we switched from RHEL7 to CentOS7 as base image we could let the Docker image be built on Docker Hub. This would allow companies with restrictive network access policies to clone the APPUiO Docker Hub registry which in turn is attached to the OpenShift installation. That way we could simply pull appuio/appuio-pruner in the Puppet module.

Is there a reason that prohibits the use of CentOS?

**Comment by dtschan** [comment]
What was blocked? Cloning the Git repository or pulling the base image from the Red Hat registry?

We can't just switch to CentOS on DockerHub:

* Some customers want to run RHEL bases images only on their clusters and have corresponding image scanning infrastructure
* For some customers pulling images directly from external registries is not an option

However it's already planed to make the base image configurable through the template like it's done here: https://github.com/appuio/haproxy.
